import { Inter } from "next/font/google";
import "./globals.css";
import { Container } from "@mui/material";
import Footer from "@/components/ContactPage/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>

      <html lang="en">
        <body className={inter.className}>
          <Container maxWidth='2xl'>
            {children}
          </Container>
          <Footer />
        </body>
      </html>
    </>
  );
}
