
import { Roboto } from "next/font/google";
import "../app/globals.css"
import { ClerkProvider } from '@clerk/nextjs';
import MainNav from "@/components/MainNav";
import { Container } from "@mui/material";
import Head from "next/head";
import Footer from "@/components/Footer";


const roboto = Roboto({
  weight: '500',
  subsets: ["latin"]
});

export const metadata = {
  title: "RMR AI",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <Head>
          <title>{metadata.title}</title>
          <meta name="description" content={metadata.description} />

        </Head>
        <body className={roboto.className}>
          <MainNav />
          <br />
          <br />
          <br />
          <Container maxWidth="lg">
            {children}
          </Container>
          <Footer />
        </body>
      </html>
    </ClerkProvider>
  );
}
